# Generated by Django 6.0.7 on 2026-08-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atuntication', '0003_category_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('des', models.CharField(max_length=150, verbose_name='توضیحات')),
                ('like', models.IntegerField(default=0, verbose_name='لایک ها')),
                ('comments', models.TextField(verbose_name='کامنت ها')),
            ],
        ),
    ]
