# Generated by Django 6.0.7 on 2026-07-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ سررسید')),
            ],
        ),
    ]
